networks:
  network-ollama:
    external: true

services:
  qwen-code:
    build:
      args:
        # Output of command: getent group docker | cut -d: -f3
        DOCKER_GID: ${DOCKER_GID:-998}
      context: .
    container_name: ${CONTAINER_NAME:-qwen-code}
    environment:
      #- OLLAMA_API=${OLLAMA_API:-http://ollama:11434}
      - TZ=${TZ:-UTC}
    # Health check
    healthcheck:
      test: ["CMD", "node", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    hostname: qwen-code
    # To use MCP ollama as docker
    #networks:
    #  - network-ollama
    volumes:
      - ${VOLUME_PROJECTS:-./projects}:/projects
      - ${VOLUME_QWEN_DATA:-./qwen_data}:/qwen_data
      # Docker socket for Docker-in-Docker (optional)
      - /var/run/docker.sock:/var/run/docker.sock
